# Generated by Django 4.2.16 on 2026-01-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0002_oauthstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialprofile",
            name="access_token",
            field=models.TextField(blank=True, db_column="access_token", null=True),
        ),
        migrations.RenameField(
            model_name="socialprofile",
            old_name="access_token",
            new_name="_access_token",
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="refresh_token",
            field=models.TextField(blank=True, db_column="refresh_token", null=True),
        ),
        migrations.RenameField(
            model_name="socialprofile",
            old_name="refresh_token",
            new_name="_refresh_token",
        ),
        migrations.AddField(
            model_name="oauthstate",
            name="code_verifier",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="oauthstate",
            name="used",
            field=models.BooleanField(default=False),
        ),
    ]
