# Generated by Django 4.2.16 on 2026-01-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0003_alter_socialprofile_access_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwitterWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("tweet_create", "Tweet Created"),
                            ("favorite", "Like/Favorite"),
                            ("follow", "New Follower"),
                            ("unfollow", "Unfollowed"),
                            ("direct_message", "Direct Message"),
                            ("tweet_delete", "Tweet Deleted"),
                            ("mention", "Mentioned"),
                            ("retweet", "Retweeted"),
                            ("quote", "Quote Tweet"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "for_user_id",
                    models.CharField(
                        db_index=True,
                        help_text="Twitter user ID this event is for",
                        max_length=50,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict, help_text="Full event payload from Twitter"
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        default=False, help_text="Whether user has seen this event"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Twitter Webhook Event",
                "verbose_name_plural": "Twitter Webhook Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["for_user_id", "-created_at"],
                        name="automation__for_use_9d33ee_idx",
                    ),
                    models.Index(
                        fields=["for_user_id", "read"],
                        name="automation__for_use_bce579_idx",
                    ),
                ],
            },
        ),
    ]
