# Generated by Django 4.2.16 on 2026-01-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0004_add_twitter_webhook_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkedInWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("share_reaction", "Share Reaction (Like)"),
                            ("share_comment", "Comment on Share"),
                            ("mention", "Mentioned"),
                            ("connection_update", "Connection Update"),
                            ("organization_update", "Organization Update"),
                            ("share_update", "Share/Post Update"),
                            ("message", "Message Received"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "for_user_id",
                    models.CharField(
                        db_index=True,
                        help_text="LinkedIn member URN this event is for",
                        max_length=100,
                    ),
                ),
                (
                    "resource_urn",
                    models.CharField(
                        blank=True,
                        help_text="URN of the resource (share, comment, etc.)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict, help_text="Full event payload from LinkedIn"
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        default=False, help_text="Whether user has seen this event"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "LinkedIn Webhook Event",
                "verbose_name_plural": "LinkedIn Webhook Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["for_user_id", "-created_at"],
                        name="automation__for_use_cb0c32_idx",
                    ),
                    models.Index(
                        fields=["for_user_id", "read"],
                        name="automation__for_use_33e8a5_idx",
                    ),
                ],
            },
        ),
    ]
