# Generated by Django 4.2.16 on 2026-01-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0005_linkedin_webhook_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialprofile",
            name="_page_access_token",
            field=models.TextField(
                blank=True, db_column="page_access_token", null=True
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="page_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
