# Generated by Django 4.2.16 on 2026-01-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0006_add_facebook_page_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("feed", "Feed Update (Post/Comment/Reaction)"),
                            ("mention", "Page Mentioned"),
                            ("message", "Message Received"),
                            ("messaging_postback", "Messaging Postback"),
                            ("rating", "Page Rating"),
                            ("video", "Video Status Change"),
                            ("leadgen", "Lead Generation"),
                            ("conversations", "Conversation Update"),
                            ("feed_comment", "Comment on Feed"),
                            ("feed_reaction", "Reaction on Feed"),
                            ("feed_share", "Post Shared"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "page_id",
                    models.CharField(
                        db_index=True,
                        help_text="Facebook Page ID this event is for",
                        max_length=100,
                    ),
                ),
                (
                    "sender_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the user who triggered the event",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "post_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the post related to this event",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict, help_text="Full event payload from Facebook"
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        default=False, help_text="Whether user has seen this event"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Facebook Webhook Event",
                "verbose_name_plural": "Facebook Webhook Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["page_id", "-created_at"],
                        name="automation__page_id_bcba2d_idx",
                    ),
                    models.Index(
                        fields=["page_id", "read"],
                        name="automation__page_id_92dc1b_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="automation__event_t_e025f8_idx",
                    ),
                ],
            },
        ),
    ]
