# Generated by Django 4.2.16 on 2026-01-16 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("automation", "0007_facebook_webhook_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookResumableUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_id",
                    models.CharField(help_text="Facebook Page ID", max_length=100),
                ),
                (
                    "upload_session_id",
                    models.CharField(
                        help_text="Facebook upload session ID",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "video_id",
                    models.CharField(
                        blank=True,
                        help_text="Video ID once upload starts",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.BigIntegerField(help_text="Total file size in bytes"),
                ),
                ("content_type", models.CharField(default="video/mp4", max_length=100)),
                (
                    "bytes_uploaded",
                    models.BigIntegerField(
                        default=0, help_text="Bytes uploaded so far"
                    ),
                ),
                (
                    "start_offset",
                    models.BigIntegerField(
                        default=0, help_text="Next byte offset to upload from"
                    ),
                ),
                (
                    "end_offset",
                    models.BigIntegerField(
                        default=0, help_text="End offset of last successful chunk"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending - Not Started"),
                            ("uploading", "Uploading - In Progress"),
                            ("processing", "Processing - Upload Complete"),
                            ("completed", "Completed - Ready"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facebook_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Facebook Resumable Upload",
                "verbose_name_plural": "Facebook Resumable Uploads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="automation__user_id_993e0d_idx"
                    ),
                    models.Index(
                        fields=["page_id", "-created_at"],
                        name="automation__page_id_027aa6_idx",
                    ),
                ],
            },
        ),
    ]
