# Generated by Django 4.2.16 on 2026-01-17 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("automation", "0008_facebook_resumable_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialprofile",
            name="_instagram_access_token",
            field=models.TextField(
                blank=True,
                db_column="instagram_access_token",
                help_text="Instagram Graph API access token",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="instagram_user_id",
            field=models.CharField(
                blank=True,
                help_text="Instagram Business Account ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="instagram_username",
            field=models.CharField(
                blank=True,
                help_text="Instagram username (handle)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="InstagramWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("comments", "Comment on Post"),
                            ("mentions", "Mentioned"),
                            ("story_mentions", "Story Mention"),
                            ("story_replies", "Story Reply"),
                            ("message_reactions", "Message Reaction"),
                            ("messages", "Direct Message"),
                            ("live_comments", "Live Video Comment"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "instagram_user_id",
                    models.CharField(
                        db_index=True,
                        help_text="Instagram Business Account ID this event is for",
                        max_length=100,
                    ),
                ),
                (
                    "sender_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the user who triggered the event",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "media_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the media (post/story) related to this event",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict, help_text="Full event payload from Instagram"
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        default=False, help_text="Whether user has seen this event"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Instagram Webhook Event",
                "verbose_name_plural": "Instagram Webhook Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["instagram_user_id", "-created_at"],
                        name="automation__instagr_3d3ccb_idx",
                    ),
                    models.Index(
                        fields=["instagram_user_id", "read"],
                        name="automation__instagr_5d7ac3_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="automation__event_t_27d88d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InstagramResumableUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instagram_user_id",
                    models.CharField(
                        help_text="Instagram Business Account ID", max_length=100
                    ),
                ),
                (
                    "container_id",
                    models.CharField(
                        blank=True,
                        help_text="Instagram media container ID",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "media_id",
                    models.CharField(
                        blank=True,
                        help_text="Published media ID once upload completes",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.BigIntegerField(help_text="Total file size in bytes"),
                ),
                ("content_type", models.CharField(default="video/mp4", max_length=100)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image Post"),
                            ("VIDEO", "Video Post"),
                            ("CAROUSEL", "Carousel Post"),
                            ("REELS", "Reels Video"),
                            ("STORIES", "Story"),
                        ],
                        default="VIDEO",
                        max_length=20,
                    ),
                ),
                (
                    "bytes_uploaded",
                    models.BigIntegerField(
                        default=0, help_text="Bytes uploaded so far"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending - Not Started"),
                            ("uploading", "Uploading - In Progress"),
                            ("processing", "Processing - Upload Complete"),
                            ("completed", "Completed - Ready"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "caption",
                    models.TextField(blank=True, help_text="Post caption", null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram Resumable Upload",
                "verbose_name_plural": "Instagram Resumable Uploads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="automation__user_id_1e8117_idx"
                    ),
                    models.Index(
                        fields=["instagram_user_id", "-created_at"],
                        name="automation__instagr_9d0de2_idx",
                    ),
                ],
            },
        ),
    ]
