# Generated by Django 5.2.10 on 2026-01-09 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="domain",
        ),
        migrations.AlterField(
            model_name="domain",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domain",
                to="tenants.tenant",
            ),
        ),
    ]
