# Generated by Django 4.2.16 on 2026-01-09 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_remove_tenant_domain_alter_domain_tenant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domain",
            options={},
        ),
        migrations.AddField(
            model_name="tenant",
            name="schema_name",
            field=models.CharField(
                blank=True, help_text="Database schema name", max_length=63, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="domain",
            field=models.CharField(db_index=True, max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="is_primary",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="tenants.tenant",
            ),
        ),
    ]
