# Generated by Django 5.2.10 on 2026-01-09 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Company/Brand name", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Brief company description"),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, help_text="Industry sector", max_length=100
                    ),
                ),
                (
                    "target_audience",
                    models.TextField(
                        blank=True, help_text="Description of target customers"
                    ),
                ),
                (
                    "core_problem",
                    models.TextField(
                        blank=True, help_text="Main problem the company solves"
                    ),
                ),
                (
                    "brand_voice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("professional", "Professional"),
                            ("friendly", "Friendly"),
                            ("bold", "Bold"),
                            ("authoritative", "Authoritative"),
                            ("playful", "Playful"),
                            ("innovative", "Innovative"),
                            ("warm", "Warm"),
                            ("technical", "Technical"),
                        ],
                        help_text="Brand personality/voice",
                        max_length=50,
                    ),
                ),
                (
                    "vision_statement",
                    models.TextField(
                        blank=True, help_text="AI-generated vision statement"
                    ),
                ),
                (
                    "mission_statement",
                    models.TextField(
                        blank=True, help_text="AI-generated mission statement"
                    ),
                ),
                (
                    "values",
                    models.JSONField(default=list, help_text="List of core values"),
                ),
                (
                    "positioning_statement",
                    models.TextField(
                        blank=True, help_text="Market positioning statement"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Brand tagline/slogan",
                        max_length=255,
                    ),
                ),
                (
                    "value_proposition",
                    models.TextField(blank=True, help_text="Key value proposition"),
                ),
                (
                    "elevator_pitch",
                    models.TextField(blank=True, help_text="30-second elevator pitch"),
                ),
                (
                    "color_palette_desc",
                    models.TextField(
                        blank=True, help_text="Color palette recommendations"
                    ),
                ),
                (
                    "font_recommendations",
                    models.TextField(
                        blank=True, help_text="Typography recommendations"
                    ),
                ),
                (
                    "messaging_guide",
                    models.TextField(
                        blank=True, help_text="Brand messaging guidelines"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="BrandAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original file name", max_length=255),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("other", "Other"),
                        ],
                        help_text="Type of file",
                        max_length=50,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "gcs_path",
                    models.CharField(
                        help_text="Google Cloud Storage path", max_length=500
                    ),
                ),
                (
                    "gcs_bucket",
                    models.CharField(default="brand-automator-assets", max_length=100),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether file has been processed",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_assets",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="onboarding.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Asset",
                "verbose_name_plural": "Brand Assets",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("company_info", "Company Information"),
                            ("brand_strategy", "Brand Strategy"),
                            ("brand_identity", "Brand Identity"),
                            ("assets_upload", "Assets Upload"),
                            ("review", "Review & Complete"),
                        ],
                        default="company_info",
                        help_text="Current onboarding step",
                        max_length=50,
                    ),
                ),
                (
                    "completed_steps",
                    models.JSONField(
                        default=list,
                        help_text="List of completed step identifiers",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether onboarding is fully complete",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_progress",
                        to="onboarding.company",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_progress",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Progress",
                "verbose_name_plural": "Onboarding Progress",
            },
        ),
    ]
