# Generated by Django 4.2.16 on 2026-01-10 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_alter_domain_options_tenant_schema_name_and_more"),
        ("onboarding", "0002_add_database_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="brandasset",
            name="onboarding_asset_company_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="brandasset",
            name="onboarding_asset_uploaded_idx",
        ),
        migrations.RemoveIndex(
            model_name="company",
            name="onboarding_company_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="company",
            name="onboarding_company_industry_idx",
        ),
        migrations.RemoveIndex(
            model_name="company",
            name="onboarding_company_tenant_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="onboardingprogress",
            name="onboarding_progress_tenant_completed_idx",
        ),
        migrations.AlterField(
            model_name="brandasset",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant (optional in MVP mode)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand_assets",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="tenant",
            field=models.OneToOneField(
                blank=True,
                help_text="Tenant (optional in MVP mode)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="onboardingprogress",
            name="tenant",
            field=models.OneToOneField(
                blank=True,
                help_text="Tenant (optional in MVP mode)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboarding_progress",
                to="tenants.tenant",
            ),
        ),
    ]
