# Generated by Django 4.2.16 on 2026-01-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0003_make_tenant_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="demographics",
            field=models.TextField(
                blank=True,
                help_text="Demographic characteristics of target audience",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="desired_outcomes",
            field=models.TextField(
                blank=True, help_text="What customers want to achieve"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="pain_points",
            field=models.TextField(
                blank=True, help_text="Customer pain points and challenges"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="psychographics",
            field=models.TextField(
                blank=True,
                help_text="Psychological characteristics, values, interests",
            ),
        ),
    ]
