# Generated by Django 5.2.10 on 2026-01-09 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("brand_strategy", "Brand Strategy"),
                            ("brand_identity", "Brand Identity"),
                            ("content", "Content Generation"),
                            ("analysis", "Market Analysis"),
                        ],
                        help_text="Type of AI-generated content",
                        max_length=50,
                    ),
                ),
                ("prompt", models.TextField(help_text="AI prompt used")),
                ("response", models.TextField(help_text="AI response generated")),
                (
                    "tokens_used",
                    models.PositiveIntegerField(
                        default=0, help_text="API tokens consumed"
                    ),
                ),
                (
                    "model_used",
                    models.CharField(default="gemini-2.0-flash-exp", max_length=100),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "processing_time",
                    models.FloatField(
                        default=0.0, help_text="Processing time in seconds"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_generations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Generation",
                "verbose_name_plural": "AI Generations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        help_text="Unique session identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Session title", max_length=255
                    ),
                ),
                (
                    "messages",
                    models.JSONField(default=list, help_text="List of chat messages"),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict, help_text="Session context (company info, etc.)"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_activity",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "ordering": ["-last_activity"],
            },
        ),
    ]
